<TwoBackgrounds>:
    Widget:
        pos_hint: {'x': 0 , 'y': 0.60}
        size_hint: 1, 0.40
        canvas:
            Color:
                rgb: 1, 1, 1
            Rectangle:
                size: self.size
                pos: self.pos
    Widget:
        pos_hint: {'x': 0, 'y' : 0}
        size_hint: 1, 0.6
        canvas:
            Color:
                rgb: 0.494, 0, 0.592
            Rectangle:
                size: self.size
                pos: self.pos
